repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.2
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
      - id: tofu_docs
        args:
          - '--args=--lockfile=false'
      - id: tofu_tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
